- name: apt-get install all basic Ruby / Rails dependencies
  apt: name={{item}}  state=installed  update_cache=yes
  become: yes
  with_items:
  - git
  - git-core
  - curl
  - zlib1g-dev
  - build-essential
  - libssl-dev
  - libreadline-dev
  - libyaml-dev
  - libsqlite3-dev
  - sqlite3
  - libxml2-dev
  - libxslt1-dev
  - libcurl4-openssl-dev
  - python-software-properties
  - libffi-dev
  - apt-transport-https
